# Generated by Django 5.0.6 on 2024-06-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="matchesTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(db_column="season", max_length=9)),
                ("date", models.DateField(db_column="date")),
                ("home", models.CharField(db_column="home", max_length=20)),
                (
                    "homeXG",
                    models.DecimalField(
                        db_column="homeXG", decimal_places=1, max_digits=3
                    ),
                ),
                ("homeGoals", models.IntegerField(db_column="homeGoals")),
                ("awayGoals", models.IntegerField(db_column="awayGoals")),
                ("awayXG", models.DecimalField(decimal_places=1, max_digits=3)),
                ("away", models.CharField(db_column="away", max_length=20)),
                ("attendance", models.IntegerField(db_column="attendance")),
                ("venue", models.CharField(db_column="venue", max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="seasonsTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(db_column="season", max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name="statsTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(db_column="season", max_length=9)),
                ("squad", models.CharField(db_column="squad", max_length=20)),
                ("wins", models.IntegerField(db_column="wins")),
                ("draws", models.IntegerField(db_column="draws")),
                ("losses", models.IntegerField(db_column="losses")),
                ("goalsF", models.IntegerField(db_column="goalsFor")),
                ("goalsA", models.IntegerField(db_column="goalsAgainst")),
                ("points", models.IntegerField(db_column="points")),
                (
                    "shots",
                    models.DecimalField(
                        db_column="shots", decimal_places=1, max_digits=5
                    ),
                ),
                (
                    "shotsOT",
                    models.DecimalField(
                        db_column="shotsOT", decimal_places=1, max_digits=5
                    ),
                ),
                (
                    "FKShots",
                    models.DecimalField(
                        db_column="FKShots", decimal_places=1, max_digits=4
                    ),
                ),
                (
                    "PKGoals",
                    models.DecimalField(
                        db_column="PKGoals", decimal_places=1, max_digits=4
                    ),
                ),
                (
                    "cmp",
                    models.DecimalField(
                        db_column="cmp", decimal_places=1, max_digits=7
                    ),
                ),
                (
                    "att",
                    models.DecimalField(
                        db_column="att", decimal_places=1, max_digits=7
                    ),
                ),
                (
                    "cmpPerc",
                    models.DecimalField(
                        db_column="cmpPerc", decimal_places=1, max_digits=4
                    ),
                ),
                (
                    "corners",
                    models.DecimalField(
                        db_column="corners", decimal_places=1, max_digits=5
                    ),
                ),
                (
                    "crdY",
                    models.DecimalField(
                        db_column="crdY", decimal_places=1, max_digits=4
                    ),
                ),
                (
                    "crdR",
                    models.DecimalField(
                        db_column="crdR", decimal_places=1, max_digits=3
                    ),
                ),
                (
                    "fouls",
                    models.DecimalField(
                        db_column="fouls", decimal_places=1, max_digits=5
                    ),
                ),
                (
                    "PKCon",
                    models.DecimalField(
                        db_column="PKCon", decimal_places=1, max_digits=3
                    ),
                ),
                (
                    "ownGoals",
                    models.DecimalField(
                        db_column="ownGoals", decimal_places=1, max_digits=3
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="teamsTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("squad", models.CharField(db_column="squad", max_length=20)),
            ],
        ),
    ]
