# Generated by Django 5.0.6 on 2024-05-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="matches",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("season", models.CharField(max_length=9)),
                ("date", models.DateField()),
                ("home", models.CharField(max_length=25)),
                ("homexG", models.DecimalField(decimal_places=1, max_digits=3)),
                ("homeGoals", models.IntegerField()),
                ("awayGoals", models.IntegerField()),
                ("awayxG", models.DecimalField(decimal_places=1, max_digits=3)),
                ("away", models.CharField(max_length=25)),
                ("attendance", models.IntegerField()),
                ("venue", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="seasons",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("season", models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name="seasonStats",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("season", models.CharField(max_length=9)),
                ("squad", models.CharField(max_length=25)),
                ("wins", models.IntegerField()),
                ("draws", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("goalsF", models.IntegerField()),
                ("goalsA", models.IntegerField()),
                ("points", models.IntegerField()),
                ("shots", models.IntegerField()),
                ("shotsOT", models.IntegerField()),
                ("freeK", models.IntegerField()),
                ("PKGoals", models.IntegerField()),
                ("passCmp", models.IntegerField()),
                ("passAtt", models.IntegerField()),
                ("passPerc", models.DecimalField(decimal_places=1, max_digits=4)),
                ("corners", models.IntegerField()),
                ("yellows", models.IntegerField()),
                ("reds", models.IntegerField()),
                ("fouls", models.IntegerField()),
                ("PKCon", models.IntegerField()),
                ("ownGoals", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="teams",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("team", models.CharField(max_length=25)),
            ],
        ),
    ]
