# Generated by Django 5.0.6 on 2024-07-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="currTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(db_column="positon")),
                ("squad", models.CharField(db_column="squad", max_length=20)),
                ("played", models.IntegerField(db_column="played")),
                ("wins", models.IntegerField(db_column="wins")),
                ("draws", models.IntegerField(db_column="draws")),
                ("losses", models.IntegerField(db_column="losses")),
                ("gf", models.IntegerField(db_column="goalsF")),
                ("ga", models.IntegerField(db_column="goalsA")),
                ("gd", models.IntegerField(db_column="goalD")),
                ("points", models.IntegerField(db_column="points")),
            ],
        ),
    ]
