# Generated by Django 5.0.6 on 2024-06-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchestbl",
            name="date",
            field=models.CharField(db_column="date", max_length=15),
        ),
    ]
