# Generated by Django 5.0.6 on 2024-06-10 00:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_matchestbl_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="matchesTbl",
        ),
    ]
