# Generated by Django 5.0.6 on 2024-06-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_rename_attendance_matches_attendance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matches",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
