# Generated by Django 5.0.6 on 2024-06-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_delete_matchestbl"),
    ]

    operations = [
        migrations.CreateModel(
            name="matchesTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(db_column="season", max_length=9)),
                ("date", models.CharField(db_column="date", max_length=15)),
                ("home", models.CharField(db_column="home", max_length=20)),
                (
                    "homeXG",
                    models.DecimalField(
                        db_column="homeXG", decimal_places=1, max_digits=3
                    ),
                ),
                ("homeGoals", models.IntegerField(db_column="homeGoals")),
                ("awayGoals", models.IntegerField(db_column="awayGoals")),
                ("awayXG", models.DecimalField(decimal_places=1, max_digits=3)),
                ("away", models.CharField(db_column="away", max_length=20)),
                ("attendance", models.IntegerField(db_column="attendance")),
                ("venue", models.CharField(db_column="venue", max_length=40)),
            ],
        ),
    ]
