# Generated by Django 5.0.6 on 2024-06-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_rename_col09_matches_attendance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matches",
            name="Attendance",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="matches",
            name="Away",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="matches",
            name="Date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="matches",
            name="Home",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="matches",
            name="Season",
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name="matches",
            name="Venue",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="matches",
            name="awayGoals",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="matches",
            name="awayxG",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name="matches",
            name="homeGoals",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="matches",
            name="homexG",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name="seasons",
            name="season",
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="Att",
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="CK",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="Cmp",
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="CmpPerc",
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="CrdR",
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="CrdY",
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="D",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="FK",
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="Fls",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="GA",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="GF",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="L",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="OG",
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="PK",
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="PKcon",
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="Pts",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="Season",
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="Sh",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="SoT",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="Squad",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="W",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="teams",
            name="team",
            field=models.CharField(max_length=25),
        ),
    ]
