# Generated by Django 5.0.6 on 2024-06-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_matches_attendance_alter_matches_away_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matches",
            name="Attendance",
            field=models.IntegerField(db_column="Attendance"),
        ),
        migrations.AlterField(
            model_name="matches",
            name="Away",
            field=models.CharField(db_column="Away Team", max_length=25),
        ),
        migrations.AlterField(
            model_name="matches",
            name="Date",
            field=models.DateField(db_column="Date"),
        ),
        migrations.AlterField(
            model_name="matches",
            name="Home",
            field=models.CharField(db_column="Home Team", max_length=25),
        ),
        migrations.AlterField(
            model_name="matches",
            name="Season",
            field=models.CharField(db_column="Season", max_length=9),
        ),
        migrations.AlterField(
            model_name="matches",
            name="Venue",
            field=models.CharField(db_column="Venue", max_length=50),
        ),
        migrations.AlterField(
            model_name="matches",
            name="awayGoals",
            field=models.IntegerField(db_column="Away Goals"),
        ),
        migrations.AlterField(
            model_name="matches",
            name="awayxG",
            field=models.DecimalField(
                db_column="Away xG", decimal_places=1, max_digits=3
            ),
        ),
        migrations.AlterField(
            model_name="matches",
            name="homeGoals",
            field=models.IntegerField(db_column="Home Goals"),
        ),
        migrations.AlterField(
            model_name="matches",
            name="homexG",
            field=models.DecimalField(
                db_column="Home xG", decimal_places=1, max_digits=3
            ),
        ),
        migrations.AlterField(
            model_name="seasons",
            name="season",
            field=models.CharField(db_column="Team", max_length=9),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="Att",
            field=models.DecimalField(
                db_column="Passes Attempted", decimal_places=1, max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="CK",
            field=models.DecimalField(
                db_column="Corner Kicks", decimal_places=1, max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="Cmp",
            field=models.DecimalField(
                db_column="Passes Completed", decimal_places=1, max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="CmpPerc",
            field=models.DecimalField(
                db_column="Pass Completion %", decimal_places=1, max_digits=4
            ),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="CrdR",
            field=models.DecimalField(
                db_column="Red Cards", decimal_places=1, max_digits=4
            ),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="CrdY",
            field=models.DecimalField(
                db_column="Yellow Cards", decimal_places=1, max_digits=4
            ),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="D",
            field=models.IntegerField(db_column="Draws"),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="FK",
            field=models.DecimalField(
                db_column="Free Kick Shots", decimal_places=1, max_digits=4
            ),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="Fls",
            field=models.DecimalField(
                db_column="Fouls", decimal_places=1, max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="GA",
            field=models.IntegerField(db_column="Goals Against"),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="GF",
            field=models.IntegerField(db_column="Goals For"),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="L",
            field=models.IntegerField(db_column="Losses"),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="OG",
            field=models.DecimalField(
                db_column="Own Goals", decimal_places=1, max_digits=4
            ),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="PK",
            field=models.DecimalField(
                db_column="PK Goals", decimal_places=1, max_digits=4
            ),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="PKcon",
            field=models.DecimalField(
                db_column="PKs Conceded", decimal_places=1, max_digits=4
            ),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="Pts",
            field=models.IntegerField(db_column="Points"),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="Season",
            field=models.CharField(db_column="Season", max_length=9),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="Sh",
            field=models.DecimalField(
                db_column="Shots", decimal_places=1, max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="SoT",
            field=models.DecimalField(
                db_column="Shots on Target", decimal_places=1, max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="Squad",
            field=models.CharField(db_column="Team", max_length=25),
        ),
        migrations.AlterField(
            model_name="seasonstats",
            name="W",
            field=models.IntegerField(db_column="Wins"),
        ),
        migrations.AlterField(
            model_name="teams",
            name="team",
            field=models.CharField(db_column="Season", max_length=25),
        ),
    ]
