# Generated by Django 5.0.6 on 2024-06-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("home", "0010_delete_matches_delete_seasons_delete_seasonstats_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="seasons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(max_length=9)),
            ],
        ),
    ]
