# Generated by Django 5.0.6 on 2024-06-01 04:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="seasons",
            new_name="seasonsTbl",
        ),
    ]
