# Generated by Django 5.0.6 on 2024-06-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_rename_seasons_seasonstbl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seasonstbl",
            name="id",
        ),
        migrations.AddField(
            model_name="seasonstbl",
            name="season_id",
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
