# Generated by Django 5.0.6 on 2024-06-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_remove_seasonstbl_id_seasonstbl_season_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonstbl",
            name="season",
            field=models.CharField(db_column="season", max_length=9),
        ),
        migrations.AlterField(
            model_name="seasonstbl",
            name="season_id",
            field=models.BigAutoField(
                db_column="season_id", primary_key=True, serialize=False
            ),
        ),
    ]
