# Generated by Django 5.0.6 on 2024-06-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_alter_seasonstbl_season_alter_seasonstbl_season_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seasonstbl",
            name="season_id",
        ),
        migrations.AddField(
            model_name="seasonstbl",
            name="id",
            field=models.BigAutoField(
                db_column="id", default=0, primary_key=True, serialize=False
            ),
        ),
    ]
