# Generated by Django 5.0.6 on 2024-06-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_remove_seasonstbl_season_id_seasonstbl_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonstbl",
            name="id",
            field=models.BigAutoField(
                db_column="id",
                default="",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
