# Generated by Django 5.0.6 on 2024-06-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_alter_seasonstbl_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonstbl",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
