# Generated by Django 5.0.6 on 2024-06-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_matchestbl"),
    ]

    operations = [
        migrations.CreateModel(
            name="teamsTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("squad", models.CharField(db_column="squad", max_length=20)),
            ],
        ),
    ]
